flowchart TD

    A[Developer Commit] --> B[GitHub Actions CI]

    B --> C[Terraform Init/Plan/Apply]
    C --> D[S3 Remote State + DynamoDB Lock]

    C --> E[VPC Module]
    C --> F[EC2 Module]
    C --> G[Security Groups]

    C --> H[Terraform Outputs]
    H --> I[Ansible Inventory File]

    B --> J[Ansible Provisioning]
    J --> K[Install Docker Engine]
    J --> L[Docker Compose Deployment]
    J --> M[Nginx Reverse Proxy + HTTPS]
    J --> N[Python Demo Application]

    M --> O[Public Endpoint]